AdaptaviveCards Adjusment
galette/galette pull request #540
Opened 2024-09-26 10:53 UTC by TheFab21

2024-09-26 13:07 UTC, trasher requested changes
Please fix CS (running `vendor/bin/phpbcf` should do the trick.)

2024-09-26 13:07 UTC, trasher commented on galette/lib/Galette/IO/PdfMembersCards.php
> +	protected int $ban_max_he;
Those ones should be declared in `PdfMembersCardsAdaptative.php` file

2024-09-27 07:53 UTC, trasher commented on galette/lib/Galette/IO/PdfMembersCards.php
> +    protected int $nb_char;
Must be declared in `PdfMembersCardsAdaptative.php`

2024-09-27 07:53 UTC, trasher commented on galette/lib/Galette/IO/PdfMembersCardsAdaptative.php
> +protected int $ban_max_he;
Incorrect. Those must be inside the class.

2024-10-10 20:07 UTC, trasher commented
I did not made much tests, it seems better globally.

I continue to have override with due date:
![image](https://github.com/user-attachments/assets/034c66e9-a5cd-4750-a71a-1f435c35f043)

Also, this date is very huge... But that's not a blocker, I'll merge this one.

2024-10-10 20:23 UTC, TheFab21 commented
Ok je vois le pb deadline ca me prendra 5 minutes à corriger 😉 quand c’est juste l’année ca va bien

 

De : Johan Cwiklinski ***@***.***> 
Envoyé : jeudi, 10 octobre 2024 22:08
À : galette/galette ***@***.***>
Cc : TheFab21 ***@***.***>; Author ***@***.***>
Objet : Re: [galette/galette] AdaptaviveCards Adjusment (PR #540)

 

I did not made much tests, it seems better globally.

I continue to have override with due date:
image.png (view on web) <https://github.com/user-attachments/assets/034c66e9-a5cd-4750-a71a-1f435c35f043> 

Also, this date is very huge... But that's not a blocker, I'll merge this one.

—
Reply to this email directly, view it on GitHub <https://github.com/galette/galette/pull/540#issuecomment-2405949400> , or unsubscribe <https://github.com/notifications/unsubscribe-auth/A43ORXZT6SFAJDALBD2P4C3Z23NBBAVCNFSM6AAAAABO4XPO6WVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDIMBVHE2DSNBQGA> .
You are receiving this because you authored the thread.  <https://github.com/notifications/beacon/A43ORXYLZFADR6OWM6BOW2DZ23NBBA5CNFSM6AAAAABO4XPO6WWGG33NNVSW45C7OR4XAZNMJFZXG5LFINXW23LFNZ2KUY3PNVWWK3TUL5UWJTUPM7P5Q.gif> Message ID: ***@***.*** ***@***.***> >

2024-10-10 20:26 UTC, merged