Fixe Size problem for $an_cot in adaptativecards
galette/galette pull request #551
Opened 2024-10-10 22:26 UTC by TheFab21

2024-10-10 22:34 UTC, TheFab21 commented
CS corrected with last update

2024-10-13 05:11 UTC, trasher requested changes

2024-10-13 05:11 UTC, trasher commented on galette/lib/Galette/IO/PdfMembersCardsAdaptative.php
> +            if (is_null($an_cot)) {
This condition does not work. I do not know exactly which problem you tried to fix here; but there is something wrong.

2024-10-13 05:14 UTC, trasher commented on galette/lib/Galette/IO/PdfMembersCardsAdaptative.php
> +            if (is_null($an_cot)) {
I've been able to reproduce and fix.

2024-10-13 05:43 UTC, trasher approved these changes

2024-10-13 05:43 UTC, merged